-- Create sql Database
create database sql_project;

-- craete Table
Create table ev_vehicles(
brand varchar(50),
model varchar(50),
years int,	
variant	Varchar (50),
price_usd int,	
drive_type varchar(50),
seating_capacity int,	
body_type varchar (20),	
weight_kg int,
safety_rating int,	
country varchar(50),
segment varchar (50),	
annual_sales int
);


-- See the created Table
Select * 
from ev_vehicles;


-- Imported data EV_market from csv to pgadmin into ev_vehicles table


-- To count how many rows into table
select count(*) 
from ev_vehicles;


-- Total Brand
select distinct brand 
from ev_vehicles;


-- Total Model
select distinct model 
from ev_vehicles;


-- How many models in each brand
select brand, Count(model) as model 
from ev_vehicles
group by brand;


-- Total sales
select sum(annual_sales) 
from ev_vehicles;


-- sales by each year
select years,sum(annual_sales) as total_sales 
from ev_vehicles
group by years
order by years;


-- sales by each brand
select brand,sum(annual_sales) as total_sales 
from ev_vehicles
group by brand
order by Total_sales desc;


-- Total Revenue generated
select sum(price_usd*annual_sales::bigint) as Revenue 
from ev_vehicles 


-- Total Revenue generated by each brand
select brand, sum(price_usd*annual_sales::bigint) as Revenue 
from ev_vehicles 
group by brand
order by revenue desc;


-- Revenue by each year
select Years, sum(price_usd*annual_sales::bigint) as Revenue 
from ev_vehicles 
group by years
order by years;


-- Top 5 Revenue genetated brand
select brand, sum(price_usd*annual_sales::bigint) as Revenue 
from ev_vehicles
group by brand
order by revenue desc
limit 5;


-- Top 5 Revenue genetated country
select country, sum(price_usd*annual_sales::bigint) as Revenue 
from ev_vehicles
group by country
order by revenue desc
limit 5;


-- Average sales in years
select years, round(avg(annual_sales),0) from ev_vehicles
group by years
order by years;


-- Maximum and Minimum sales
select max(annual_sales)as Max_sale, min(annual_sales) as Min_sale
from ev_vehicles;
